---
- hosts: all
  become: yes 
  gather_facts: yes
  tasks: 
  - name: i want to install apache2
    apt: 
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start apache2
    service: 
      name: apache2
      state: restarted
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on redhat
    yum: 
      name: apache2
      state: present
    when: ansible_os_family =="RedHat"

  - name: i want to restart my webserver
    service: 
      name: apache2
      state: started
    when: ansible_os_family =="RedHat"