---
- hosts: 172.31.15.94
  become: yes
  tasks: 
  - include_tasks: myfiles.yml
  - name: i want to install webserver
    apt: 
      name: apache2
      state: present
      
  - name: i want to copy static file into ansible node
    template: 
      src: mystatic.html
      dest: /var/www/html/index.html