---
- hosts: 172.31.15.94
  become: yes
  tasks: 
  - name: i want to install webserver
    apt: 
      name: apache2
      state: present

  - name: i want to copy static file into ansible node
    template: 
      src: mystatic.html
      dest: /var/www/html/index.html
    
  - name: i want to copy dynamic files into ansible node
    template: 
      src: myindex.j2
      dest: /var/www/html/index.html